services:
  pluxra:
    image: ghcr.io/felixkriechbaum/pluxra:latest
    ports:
      - "3000:3000"
    environment:
      NUXT_DB_URL: mysql://user:password@host:3306/pluxra
      NUXT_FIREBASE_PROJECT_ID: your-project-id
      NUXT_FIREBASE_CLIENT_EMAIL: your-client-email@your-project.iam.gserviceaccount.com
      NUXT_FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
      NUXT_PUBLIC_FIREBASE_API_KEY: your-api-key
      NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN: your-project.firebaseapp.com
      NUXT_PUBLIC_FIREBASE_PROJECT_ID: your-project-id
    restart: unless-stopped
